remote_theme: the-256-foundation/midnight-theme
title: Libre Board
description: Open Source Bitcoin Mining Control Board
github:
  repository_url: https://github.com/The-256-Foundation/Libre-Board
  owner_url: https://256foundation.org
